---
title: ""
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
```
 
```{r, echo = FALSE}

  sliderInput(
    'variance', label = 'variance:',
    max = 5, 
    min = 0.5,
    value = 1, 
    step = .1
  )
  
  renderPlot({
    library(mvtnorm)
    
    cor2cov <- function(R,sd2){
      S <- c(sd2, sd2)
      diag(S) %*% R %*% diag(S)
    }
  
    C <- cbind(c(1, .2), c(.2, 1))
    Sigma <- cor2cov(C, input$variance)
    x <- seq(-3, 3,  .5)
    y <- x
    z <- matrix(0,length(x),length(y))
    for(i in 1:length(x)){
      for(j in 1:length(y)){
        z[i,j] <- dmvnorm(c(x[i],y[j]), sigma = Sigma)
      }
    }
    # f <- function(x, y) { dmvnorm(c(x,y), sigma = Sigma)}
    # z <- outer(x, y, f)
    # df <- as.data.frame(expand.grid(x = seq(-3,3,.5), y = seq(-3,3,.5)))
    # df$z <- 0
    # for(i in 1:nrow(df)){
    #   df$z[i] <- dmvnorm(c(df$x[i], df$y[i]), sigma = Sigma)
    # }
    persp(x, y, -log(z), zlim = range(0,12))
    print(round(-solve(Sigma),3))
  
  })
```
